In [1]:
import torch
import numpy as np
np_data =  np.array([[0,-1],[-3,4]])
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print("np_data",np_data)
print("torch_data",torch_data)
print("tensor2array",tensor2array)
print("abs",torch.abs(torch_data))

np_data [[ 0 -1]
 [-3  4]]
torch_data tensor([[ 0, -1],
        [-3,  4]])
tensor2array [[ 0 -1]
 [-3  4]]
abs tensor([[0, 1],
        [3, 4]])


In [2]:
print("\nnumpy",np.dot(np_data,np_data))
print("\ntorch",torch.dot(torch_data.view(-1),torch_data.view(-1)))



numpy [[  3  -4]
 [-12  19]]

torch tensor(26)


In [3]:
from torch.autograd import Variable
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor,requires_grad = True)
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print("\nt_out",t_out,
      "\nv_out",v_out)



t_out tensor(7.5000) 
v_out tensor(7.5000, grad_fn=<MeanBackward0>)


In [4]:
v_out.backward()
print(variable)
print(variable.grad)
print(variable.data)
print(variable.data.numpy())

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
